#!/usr/bin/env python3
"""Validate per-file coverage thresholds from a coverage.py XML report."""

from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


class ThresholdError(ValueError):
    """Raised when a threshold argument is malformed."""


def parse_threshold(raw: str) -> tuple[str, float]:
    if "=" not in raw:
        raise ThresholdError(f"Invalid --threshold '{raw}': expected '<file>=<percent>'.")

    file_path, raw_percent = raw.split("=", maxsplit=1)
    file_path = file_path.strip()
    if not file_path:
        raise ThresholdError(f"Invalid --threshold '{raw}': file path cannot be empty.")

    try:
        percent = float(raw_percent)
    except ValueError as exc:
        raise ThresholdError(
            f"Invalid --threshold '{raw}': '{raw_percent}' is not a number."
        ) from exc

    if percent < 0 or percent > 100:
        raise ThresholdError(
            f"Invalid --threshold '{raw}': percentage must be between 0 and 100."
        )

    return file_path, percent


def normalize_path(raw_path: str) -> str:
    return raw_path.replace("\\", "/").lstrip("./")


def extract_file_coverages(coverage_xml: Path) -> dict[str, float]:
    tree = ET.parse(coverage_xml)
    root = tree.getroot()

    results: dict[str, float] = {}
    for cls in root.findall(".//class"):
        filename = cls.get("filename")
        line_rate = cls.get("line-rate")
        if not filename or line_rate is None:
            continue

        normalized = normalize_path(filename)
        results[normalized] = float(line_rate) * 100.0

    return results


def resolve_coverage(
    target: str, coverages: dict[str, float]
) -> tuple[str | None, float | None]:
    normalized_target = normalize_path(target)

    if normalized_target in coverages:
        return normalized_target, coverages[normalized_target]

    for filename, pct in coverages.items():
        if filename.endswith(normalized_target):
            return filename, pct

    return None, None


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Check per-file coverage thresholds from coverage.xml output."
    )
    parser.add_argument(
        "--coverage-xml",
        default="coverage.xml",
        help="Path to coverage XML report generated by coverage.py/pytest-cov.",
    )
    parser.add_argument(
        "--threshold",
        action="append",
        required=True,
        help="Per-file threshold in the format '<file>=<percent>'. Can be repeated.",
    )

    args = parser.parse_args()
    coverage_xml = Path(args.coverage_xml)

    if not coverage_xml.exists():
        print(f"ERROR: Coverage XML report not found: {coverage_xml}", file=sys.stderr)
        return 2

    try:
        thresholds = [parse_threshold(value) for value in args.threshold]
    except ThresholdError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    coverages = extract_file_coverages(coverage_xml)
    if not coverages:
        print(
            f"ERROR: No per-file coverage entries found in {coverage_xml}.",
            file=sys.stderr,
        )
        return 2

    failures: list[str] = []
    print("Per-file coverage checks:")

    for target, min_pct in thresholds:
        resolved_name, actual_pct = resolve_coverage(target, coverages)
        if actual_pct is None or resolved_name is None:
            failures.append(f"- {target}: file not found in coverage report")
            continue

        status = "OK" if actual_pct >= min_pct else "FAIL"
        print(
            f"  [{status}] {target} (report: {resolved_name}) => "
            f"{actual_pct:.2f}% (required: {min_pct:.2f}%)"
        )

        if actual_pct < min_pct:
            failures.append(
                f"- {target}: {actual_pct:.2f}% < required {min_pct:.2f}%"
            )

    if failures:
        print("\nCoverage threshold failures:", file=sys.stderr)
        for failure in failures:
            print(failure, file=sys.stderr)
        return 1

    print("All per-file coverage thresholds satisfied.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
