targets:
  - file: target/src/algorithms/reduce_sum.py
    function: reduce_sum
    purity: true
    max_cyclomatic: 12
    operators:
      - CONST_TUNE
      - EQ_REWRITE
      - INLINE
      - EXTRACT
      - DEADCODE_ELIM
      - MICRO_MEMO
