from __future__ import annotations

import ast
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from singular.governance.policy import MutationGovernancePolicy
from singular.memory import read_skills, write_skills

from .skill_catalog import refresh_skill_catalog


@dataclass(frozen=True)
class SkillGenesisResult:
    accepted: bool
    skill_name: str
    target: Path
    reason: str
    policy_level: str
    rolled_back: bool = False


def _utc_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _safe_skill_name(seed: str) -> str:
    normalized = "".join(ch.lower() if ch.isalnum() else "_" for ch in seed).strip("_")
    if not normalized:
        normalized = "autogen_skill"
    while "__" in normalized:
        normalized = normalized.replace("__", "_")
    return normalized


def _render_skill_template(skill_name: str) -> str:
    return (
        '"""Auto-generated skill scaffold.\n'
        "Created by life.skill_genesis with governance safeguards.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n\n"
        "def run(context: dict | None = None) -> dict:\n"
        '    """Run a deterministic safe placeholder skill."""\n'
        "    context = context or {}\n"
        "    return {\n"
        f'        "skill": "{skill_name}",\n'
        '        "status": "ready",\n'
        '        "received_keys": sorted(context.keys()),\n'
        "    }\n"
    )


def _append_journal(mem_dir: Path, payload: dict[str, object]) -> None:
    journal = mem_dir / "skill_genesis.jsonl"
    journal.parent.mkdir(parents=True, exist_ok=True)
    with journal.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(payload, ensure_ascii=False) + "\n")


def create_skill(
    *,
    skills_dir: Path,
    mem_dir: Path,
    governance_policy: MutationGovernancePolicy,
    trigger: str,
    signal_snapshot: dict[str, object],
) -> SkillGenesisResult:
    stem = _safe_skill_name(f"autogen_{trigger}")
    suffix = 0
    target = skills_dir / f"{stem}.py"
    while target.exists():
        suffix += 1
        target = skills_dir / f"{stem}_{suffix}.py"
    skill_name = target.stem

    proposal = governance_policy.simulate_write(
        target,
        root=skills_dir.parent,
        operation="skill_creation",
    )
    if not proposal.allowed:
        _append_journal(
            mem_dir,
            {
                "ts": _utc_iso(),
                "event": "skill_genesis_rejected",
                "skill": skill_name,
                "target": str(target),
                "policy_level": proposal.level,
                "reason": proposal.reason,
                "trigger": trigger,
            },
        )
        return SkillGenesisResult(
            accepted=False,
            skill_name=skill_name,
            target=target,
            reason=proposal.reason,
            policy_level=proposal.level,
        )

    source = _render_skill_template(skill_name)
    skills_before = read_skills(mem_dir / "skills.json")
    target_created = False
    try:
        ast.parse(source)
        decision = governance_policy.enforce_write(
            target,
            source,
            root=skills_dir.parent,
            operation="skill_creation",
        )
        if not decision.allowed:
            return SkillGenesisResult(
                accepted=False,
                skill_name=skill_name,
                target=target,
                reason=decision.reason,
                policy_level=decision.level,
            )
        target_created = True
        skills_after = dict(skills_before)
        skills_after[skill_name] = {
            "score": 0.0,
            "note": "auto-generated by skill genesis",
            "created_at": _utc_iso(),
            "trigger": trigger,
        }
        write_skills(skills_after, mem_dir / "skills.json")
        refresh_skill_catalog(skills_dir=skills_dir, mem_dir=mem_dir)
        _append_journal(
            mem_dir,
            {
                "ts": _utc_iso(),
                "event": "skill_genesis_created",
                "skill": skill_name,
                "target": str(target),
                "policy_level": decision.level,
                "reason": decision.reason,
                "trigger": trigger,
                "signals": signal_snapshot,
            },
        )
        return SkillGenesisResult(
            accepted=True,
            skill_name=skill_name,
            target=target,
            reason=decision.reason,
            policy_level=decision.level,
        )
    except Exception as exc:
        if target_created and target.exists():
            target.unlink()
        write_skills(skills_before, mem_dir / "skills.json")
        _append_journal(
            mem_dir,
            {
                "ts": _utc_iso(),
                "event": "skill_genesis_rolled_back",
                "skill": skill_name,
                "target": str(target),
                "trigger": trigger,
                "error": str(exc),
            },
        )
        return SkillGenesisResult(
            accepted=False,
            skill_name=skill_name,
            target=target,
            reason=f"generation failed: {exc}",
            policy_level="rollback",
            rolled_back=True,
        )

